---
- name: Include vault vars
  ansible.builtin.include_vars:
    file: vault.yml

- name: Run RabbitMQ
  community.docker.docker_container:
    name: rabbitmq
    image: 'rabbitmq:{{ rmq_image_tag }}-management'
    state: started
    restart_policy: unless-stopped
    published_ports:
      - '15672:15672'
      - '5672:5672'
    env:
      RABBITMQ_DEFAULT_USER: '{{ rmq_username }}'
      RABBITMQ_DEFAULT_PASS: '{{ rmq_password }}'
