base_packages:
  - curl
  - wget
  - vim
  - htop
  - git
  - ufw
  - unattended-upgrades
  - python3-requests

ssh_port: 22
ssh_permit_root_login: 'prohibit-password'
ssh_password_authentication: 'no'
