---
- name: Include vault vars
  ansible.builtin.include_vars:
    file: vault.yml

- name: Create /usr/share/keyrings directory
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: Add PGP to keyrings
  ansible.builtin.shell:
    cmd: curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
    creates: /usr/share/keyrings/cloudflare-main.gpg

- name: Add Cloudflare repo to apt-get
  ansible.builtin.shell:
    cmd: echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared any main' | tee /etc/apt/sources.list.d/cloudflared.list
    creates: /etc/apt/sources.list.d/cloudflared.list

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Cloudflared package
  ansible.builtin.apt:
    name: cloudflared
    state: present

- name: Install cloudflared as a service
  ansible.builtin.shell:
    cmd: cloudflared service install {{ cloudflared_token }}
    creates: /etc/systemd/system/cloudflared.service
